// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkicxvmugfqimqnabmmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhraWN4dm11Z2ZxaW1xbmFibW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMTkzNjEsImV4cCI6MjA3NDc5NTM2MX0.3oY8VPgIrtCA5WYYdaQALsavHwltypmDV53JEIj4fa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});